export enum ErrorCode {
  // Validation errors (400)
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',

  // Authentication errors (401)
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',

  // Authorization errors (403)
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Not found errors (404)
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  GYM_NOT_FOUND = 'GYM_NOT_FOUND',
  MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
  TRAINER_NOT_FOUND = 'TRAINER_NOT_FOUND',
  MEMBERSHIP_PLAN_NOT_FOUND = 'MEMBERSHIP_PLAN_NOT_FOUND',
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_NOT_FOUND',
  CHECK_IN_NOT_FOUND = 'CHECK_IN_NOT_FOUND',

  // Conflict errors (409)
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  GYM_ALREADY_EXISTS = 'GYM_ALREADY_EXISTS',
  MEMBER_ALREADY_EXISTS = 'MEMBER_ALREADY_EXISTS',
  TRAINER_ALREADY_EXISTS = 'TRAINER_ALREADY_EXISTS',
  MEMBERSHIP_PLAN_ALREADY_EXISTS = 'MEMBERSHIP_PLAN_ALREADY_EXISTS',
  ACTIVE_SUBSCRIPTION_ALREADY_EXISTS = 'ACTIVE_SUBSCRIPTION_ALREADY_EXISTS',

  // Server errors (500)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  FAILED_TO_CREATE_USER = 'FAILED_TO_CREATE_USER',
  FAILED_TO_SEND_OTP = 'FAILED_TO_SEND_OTP',

  // Too many requests (429)
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Registration specific errors (400)
  REGISTRATION_SESSION_EXPIRED = 'REGISTRATION_SESSION_EXPIRED',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_INVALID = 'OTP_INVALID',
  OTP_ATTEMPTS_EXCEEDED = 'OTP_ATTEMPTS_EXCEEDED',
  REGISTRATION_LINK_INVALID = 'REGISTRATION_LINK_INVALID',
  REGISTRATION_LINK_EXPIRED = 'REGISTRATION_LINK_EXPIRED',
  REGISTRATION_RATE_LIMITED = 'REGISTRATION_RATE_LIMITED',
  PENDING_REGISTRATION_EXISTS = 'PENDING_REGISTRATION_EXISTS',
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',
  VERIFICATION_FAILED = 'VERIFICATION_FAILED',
  PASSWORD_RESET_TOKEN_INVALID = 'PASSWORD_RESET_TOKEN_INVALID',
  PASSWORD_RESET_TOKEN_EXPIRED = 'PASSWORD_RESET_TOKEN_EXPIRED',
  PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED',

  // Admin specific errors (403)
  ADMIN_ALREADY_EXISTS = 'ADMIN_ALREADY_EXISTS',
}
