[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name             tail
    Path             /app/logs/*.json
    Parser           json
    Tag              app.logs
    Refresh_Interval 1

[OUTPUT]
    Name            opensearch
    Match           app.logs
    Host            opensearch
    Port            9200
    Index           app-logs
    Type            _doc
    Suppress_Type_Name On
    HTTP_User       ${OPENSEARCH_ADMIN_USER}
    HTTP_Passwd     ${OPENSEARCH_ADMIN_PASSWORD}
    tls             On
    tls.verify      Off
    Trace_Output    Off
    Trace_Error     On
